### ISSUE TITLE
can not use this package, undefined control sequence

### ISSUE THREAD

**Issue by jdhao** [Skillmon/ltx_ducksay#1]
Hello, this is an interesting package. I tried to use it but met with error messages. In the documentation, it says the dependency is `xparse` and `l3keys2e`. I have verified that these two packages are installed on my system.  My simple script is like the following,

```
\documentclass{article}
\usepackage{ducksay}

\begin{document}
\ducksay[duck]{hello~}

\end{document}
```
If I use `pdflatex` to compile the file, the error message is 
>! Undefined control sequence.
>l.27 \regex_new:N
>                 \l_ducksay_ligatures_regex

Is there anything wrong with my use of this package?

# system info
- platform: Windows 8.1
- LaTeX distribution: TeX Live 2016

**Comment by Skillmon** [comment]
My guess is that your version of l3 (LaTeX3 on which `xparse` depends) is too old. `\regex_new:N` was introduced in 2017/05/26. Update your TeXLive distribution to the latest version. I use l3 in the package, but at top level require `xparse` which loads it anyway, so I didn't count it as a requirement.

**Comment by Skillmon** [comment]
Appart from the version issues of your TL distribution, there is an issue with the MWE you provided. Because of the expansion of the message for the width-detection, `~` is not counted as requiring one space but 7. Therefore the spacing will be wrong. Just use ordinary spaces (with the current version, there is no linewrapping anyway, so there is absolutely no need to use a protected space with `~`).

**Comment by stefanct** [comment]
On older distributions (debian stretch) (additionally or exclusively) loading package `l3regex` instead of `expl3` might fix the problem. This worked fine for me in another circumstance:

    % \regex_new:N was provided by l3regex which was merged with expl3 later
    % This fixes compilation on Debian Stretch
    \IfFileExists{l3regex.sty}{
        \usepackage{l3regex}
    }{}
    \usepackage{expl3}

**Comment by Skillmon** [comment]
@stefanct yes, still won't fix. Policy is that I don't support out of date installations (pre 2017 is two years old, shipped distribution on Ubuntu is TL2018 frozen, on Debian only oldstable and stable ship too old TL versions), while this fix would be easy to implement it would loosen this policy. Sorry. Next version's documentation will feature a paragraph on old LaTeX installations and that you might fix issues with `\usepackage{l3regex}`.

**Comment by stefanct** [comment]
NP, I am not using your package (TBH I have no idea what it does :) But even then I would support your plan and would probably do the same thing myself (although AFAICT the fix I posted is less ugly than most backwards compatible fixes in latex I had to make previously :D). I was just documenting this here because it is one of the top items shown by search engines when one looks for the error message. Cheers and thanks!
